# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-20 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes_books', '0002_auto_20180220_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='liked_users',
            field=models.ManyToManyField(db_table='likes_books_likes', related_name='liked_books', to='likes_books.User'),
        ),
    ]
